export default {
    index: {
        type: 'page',
        title: 'Bref',
        display: 'hidden',
        // v2 used theme.layout: 'raw' (REMOVED in v4). Full-width + strip docs chrome:
        theme: {
            layout: 'full',
            sidebar: false,
            toc: false,
            breadcrumb: false,
            pagination: false,
            timestamp: false,
            footer: true,
            copyPage: false,
        },
    },
    docs: {
        type: 'page',
        title: 'Documentation',
    },
    news: {
        title: 'News',
        type: 'page',
        display: 'hidden',
        theme: { typesetting: 'article' },
    },
    cloud: {
        type: 'page',
        title: 'Bref Cloud',
        theme: {
            layout: 'full',
            sidebar: false,
            toc: false,
            breadcrumb: false,
            pagination: false,
            timestamp: false,
            copyPage: false,
        },
    },
    support: {
        type: 'page',
        title: 'Support',
        theme: {
            layout: 'full',
            sidebar: false,
            toc: false,
            breadcrumb: false,
            pagination: false,
            timestamp: false,
            copyPage: false,
        },
    },
    credits: {
        type: 'page',
        title: 'Credits',
        display: 'hidden',
        theme: {
            layout: 'full',
            sidebar: false,
            toc: false,
            breadcrumb: false,
            pagination: false,
            timestamp: false,
            copyPage: false,
        },
    },
    sentry: {
        type: 'page',
        title: 'Sentry integration for PHP on AWS Lambda',
        display: 'hidden',
        theme: {
            layout: 'full',
            sidebar: false,
            toc: false,
            breadcrumb: false,
            pagination: false,
            timestamp: false,
            copyPage: false,
        },
    },
    xray: {
        type: 'page',
        title: 'X-Ray integration for PHP',
        display: 'hidden',
        theme: {
            layout: 'full',
            sidebar: false,
            toc: false,
            breadcrumb: false,
            pagination: false,
            timestamp: false,
            copyPage: false,
        },
    },
}
