name: Deploy Docker images

on:
  push:
    tags:
      - '*' # On all tags

jobs:
  publish:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build images
        run: make docker-images

      - name: Publish
        env:
          DOCKER_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: make publish-docker-images
