#!/usr/bin/env php
<?php
declare(strict_types=1);

use GuzzleHttp\Psr7\Stream;
use PhpLambda\Util\CommandRunner;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Yaml\Yaml;

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} else {
    require_once __DIR__ . '/../../autoload.php';
}

$app = new Silly\Application;

$app->command('init', function (SymfonyStyle $io) {
    $fs = new Filesystem;
    if (!file_exists('serverless.yml')) {
        $io->writeln('Creating serverless.yml');
        $fs->copy(__DIR__ . '/template/serverless.yml', 'serverless.yml');
    }
    if (!file_exists('lambda.php')) {
        $io->writeln('Creating lambda.php');
        $fs->copy(__DIR__ . '/template/lambda.php', 'lambda.php');
    }
    $io->success([
        'Project initialized and ready to deploy using "phplambda deploy"',
        'If you are using git, you will need to commit the following files:',
        '- lambda.php',
        '- serverless.yml',
        'You can add `/.phplambda/` to your .gitignore:',
    ]);
});

$app->command('deploy', function (SymfonyStyle $io) {
    $fs = new Filesystem;
    $commandRunner = new CommandRunner;

    $io->writeln('Cloning the project in the `.phplambda` directory');
    $fs->remove('.phplambda');
    $fs->mkdir('.phplambda');

    if (!$fs->exists('.git')) {
        $currentDirectory = getcwd();
        $io->error("The directory `$currentDirectory` is not a git repository");
        return 1;
    }
    // TODO check if there are uncommitted changes in the directory, warn the user that these will not be deployed
    $commandRunner->run('cd .phplambda && git clone .. .');

    $io->writeln('Installing PHP in the `bin/` directory');
    $fs->mkdir('.phplambda/bin');
    if (!$fs->exists('.phplambda/bin/php')) {
        $commandRunner->run('curl -sSL https://lambci.s3.amazonaws.com/binaries/libtidy-0.99.tgz | tar -xz -C .phplambda/bin');
        $commandRunner->run('curl -sSL https://lambci.s3.amazonaws.com/binaries/libmcrypt-4.4.8.tgz | tar -xz -C .phplambda/bin');
        $commandRunner->run('curl -sSL https://lambci.s3.amazonaws.com/binaries/php-7.1.2.tgz | tar -xz -C .phplambda/bin');
        $fs->rename('.phplambda/bin/7.1.2', '.phplambda/bin/php');
        $fs->remove('.phplambda/bin/php/etc/conf.d/xdebug.ini'); // disable xdebug
    }

    $io->writeln('Installing `handler.js`');
    $fs->copy(__DIR__ . '/template/handler.js', '.phplambda/handler.js');

    $commandRunner->run('cd .phplambda && composer install --no-dev --classmap-authoritative');

    // TODO check there is a lambda.php file

    // Run build hooks defined in .phplambda.yml
    if ($fs->exists('.phplambda/.phplambda.yml')) {
        $config = Yaml::parse(file_get_contents('.phplambda/.phplambda.yml'));
        $buildHooks = $config['hooks']['build'] ?? [];
        foreach ($buildHooks as $buildHook) {
            $io->writeln('Running ' . $buildHook);
            $commandRunner->run('cd .phplambda && ' . $buildHook);
        }
    }

    $commandRunner->run('cd .phplambda && serverless deploy');
});

$app->command('cli [arguments]*', function (array $arguments, SymfonyStyle $io) {
    $commandRunner = new CommandRunner;

    $serverlessInfo = $commandRunner->run('serverless info');
    foreach (explode(PHP_EOL, $serverlessInfo) as $line) {
        if (strpos($line, 'region: ') === 0) {
            $region = substr($line, strlen('region: '));
        }
        if (strpos($line, 'stack: ') === 0) {
            $functionName = substr($line, strlen('stack: ')) . '-main';
        }
    }
    if (empty($region) || empty($functionName)) {
        throw new Exception('Unable to parse the output of `serverless info`');
    }

    $lambda = new \Aws\Lambda\LambdaClient([
        'version' => 'latest',
        'region' => $region,
    ]);
    $result = $lambda->invoke([
        'FunctionName' => $functionName,
        'LogType' => 'Tail',
        'Payload' => json_encode([
            'cli' => implode(' ', $arguments),
        ]),
    ]);

    /** @var Stream $payload */
    $payload = $result->get('Payload');
    $payload = json_decode($payload->getContents(), true);
    if (isset($payload['output'])) {
        $io->writeln($payload['output']);
    } else {
        $io->error('The command did not return a valid response.');
        $io->writeln('<info>Logs:</info>');
        $io->write('<comment>' . base64_decode($result->get('LogResult')) . '</comment>');
        $io->writeln('<info>Lambda result payload:</info>');
        $io->writeln(json_encode($payload, JSON_PRETTY_PRINT));
        return 1;
    }

    return (int) ($payload['exitCode'] ?? 1);
});

$app->run();
