#!/bin/sh

# Fail on error
set -e

while true
do
    # We redirect stderr to stdout so that everything
    # written on the output ends up in Cloudwatch automatically
    /opt/bin/php "/opt/bref/bootstrap.php" 2>&1
done
