#!/bin/sh

# Start NewRelic daemon
/opt/bref/bin/newrelic-daemon -c /opt/bref/etc/newrelic/newrelic.cfg

# Start PHP-FPM
/opt/bin/php-fpm --nodaemonize --fpm-config /opt/bref/etc/php-fpm.conf -d opcache.validate_timestamps=1 --force-stderr
