version: 0.2

# AWS suggests this file not be stored within the project itself for AWS Public CodeBuild
# (https://docs.aws.amazon.com/codebuild/latest/userguide/public-builds.html).
# However, what protects us here is the fact that this build WILL ONLY be executed if a PULL_REQUEST_MERGED event
# is triggered. Therefore, only AFTER a Bref Maintainer has approved and merged the changes this file will
# be executed. Changes made here that are not merged does not run the public build.
# Even if a "contributor" makes changes to the release.yml template itself to include more triggers, it requires
# manually applying those changes to AWS CloudFormation before they take effect.

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    on-failure: abort
    commands:
      # We need to resolve these variables on-the-fly because public AWS CodeBuild projects show them as plain-text
      - export GITHUB_TOKEN=$(aws ssm get-parameter --name /bref-layers-builder/github/token --output text --query Parameter.Value)
      - export DOCKER_HUB_USERNAME=$(aws ssm get-parameter --name /bref-layers-builder/docker/hub/username --output text --query Parameter.Value)
      # WARNING: Be very careful when merging pull requests that change this line. If a "contributor" changes this line to echo ${DOCKER_HUB_PASSWORD}, it will show up on the public logs.
      - export DOCKER_HUB_PASSWORD=$(aws ssm get-parameter --name /bref-layers-builder/docker/hub/password --output text --query Parameter.Value)
      - export DOCKER_BUILDKIT=1
      - export AWS_STS_REGIONAL_ENDPOINTS=regional

      # WARNING: Be very careful when merging pull requests that change this file. If a "contributor" changes this line to echo ${DOCKER_HUB_PASSWORD}, it will show up on the public logs.
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

  build:
    on-failure: abort
    commands:
      # Install GH CLI
      - curl https://cli.github.com/packages/rpm/gh-cli.repo --output /etc/yum.repos.d/gh-cli.repo
      - yum install -y gh

      # Configure GitHub User & Branch
      - git config --global user.email "deleugyn+bref@gmail.com"
      - git config --global user.name "Brefphp Bot by @deleugyn"
      - git checkout runtime
      - git checkout -b bref/layers-v2

      # Copy AWS config to be able to automatically assume role into the layer account
      - mkdir ~/.aws && cp ./runtime/aws/config ~/.aws/config

      - cd runtime && AWS_PROFILE=layer make everything

      - |
        echo -en 'layers.json update\n\nCo-authored-by: Marco Deleu <deleugyn@gmail.com>' > git-message
      - git commit -a --file git-message

      - git remote add github https://brefphp-bot:${GITHUB_TOKEN}@github.com/brefphp-bot/bref.git
      - git push --set-upstream github bref/layers-v2 --force