<?php declare(strict_types=1);

# This list has been copied from the AWS Console and kept as-is.

$console = [
    'US East (N. Virginia)us-east-1',
    'US East (Ohio)us-east-2',
    'US West (N. California)us-west-1',
    'US West (Oregon)us-west-2',
    'Africa (Cape Town)af-south-1',
    'Asia Pacific (Hong Kong)ap-east-1',
    'Asia Pacific (Mumbai)ap-south-1',
    'Asia Pacific (Osaka)ap-northeast-3',
    'Asia Pacific (Seoul)ap-northeast-2',
    'Asia Pacific (Singapore)ap-southeast-1',
    'Asia Pacific (Sydney)ap-southeast-2',
    'Asia Pacific (Tokyo)ap-northeast-1',
    'Canada (Central)ca-central-1',
    'Europe (Frankfurt)eu-central-1',
    'Europe (Ireland)eu-west-1',
    'Europe (London)eu-west-2',
    'Europe (Milan)eu-south-1',
    'Europe (Paris)eu-west-3',
    'Europe (Stockholm)eu-north-1',
    'Middle East (Bahrain)me-south-1',
    'South America (São Paulo)sa-east-1',
];

# We're looking for:
#  [a-z]{2} -> 2 letters
#  -        -> a dash
#  [a-z]+   -> any amount of letters
#  -        -> a dash
#  \d       -> a digit
$pattern = '/([a-z]{2}-[a-z]+-\d)/';

$collection = array_map(function ($item) use ($pattern) {
    $match = [];

    preg_match($pattern, $item, $match);

    $region = $match[0];

    $label = str_replace($region, '', $item);

    return ['region' => $region, 'label' => $label];
}, $console);

$file = "# This file is generated by runtime/common/publish/generate.php" . PHP_EOL;
$file .= "version: '3.8'" . PHP_EOL . PHP_EOL;
$file .= "services:" . PHP_EOL;

foreach ($collection as $item) {
    $region = $item['region'];

    $label = $item['label'];

    $file .= "  $region: # $label" . PHP_EOL;
    $file .= "    image: amazon/aws-cli" . PHP_EOL;
    $file .= "    entrypoint: /bin/bash" . PHP_EOL;
    $file .= "    command: /publish.sh" . PHP_EOL;
    $file .= "    environment: [REGION=$region, AWS_PROFILE, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN, CPU, PHP_VERSION, TYPE]" . PHP_EOL;
    $file .= "    volumes: [./publish.sh:/publish.sh, ~/.aws:/root/.aws, /tmp/bref-zip/:/tmp/bref-zip/]" . PHP_EOL;
    $file .= PHP_EOL;
}

file_put_contents(__DIR__ . '/docker-compose.yml', $file);
