module.exports.redirects = {
    '/slack': 'https://join.slack.com/t/brefworkspace/shared_invite/enQtNTcwMjU2NTcxNjAxLTIxYmM2MmRjMDkzYjdjYTNkMmE5NGI3YTcyZjc2ZGRjNTFmNjFmYzk5NWQ1YmVhMDkwNzExNzhjZThkZWM0ODE',
    '/#ecosystem': '/support',
    '/#plans': '/support',
    '/#enterprise': '/support',
    '/docs/environment/custom-domains': '/docs/use-cases/http/custom-domains',
    '/docs/aws-cdk': '/docs/deploy/aws-cdk',
    '/docs/web-apps/index.md#assets': '/docs/use-cases/websites',
    '/docs/function/local-development': '/docs/local-development/event-driven-functions',
    '/docs/frameworks/laravel': '/docs/laravel/getting-started',
    '/docs/newsletters': '/docs/community#newsletters',
    '/docs/newsletters.html': '/docs/community#newsletters',
    '/docs/cron.html': '/docs/use-cases/cron',
    '/docs/web-apps/cron.html': '/docs/use-cases/cron',
    '/docs/local-development.html': '/docs/local-development',
    '/docs/web-apps/local-development.html': '/docs/local-development',
};
