module.exports.redirects = {
    '/slack': 'https://join.slack.com/t/brefworkspace/shared_invite/enQtNTcwMjU2NTcxNjAxLTIxYmM2MmRjMDkzYjdjYTNkMmE5NGI3YTcyZjc2ZGRjNTFmNjFmYzk5NWQ1YmVhMDkwNzExNzhjZThkZWM0ODE',
    '/#ecosystem': '/support',
    '/#plans': '/support',
    '/#enterprise': '/support',
    // TODO: add redirects for anchor links too
    '/docs/news': '/news',
    '/docs/news/01-bref-1.0': '/news/01-bref-1.0',
    '/docs/news/02-bref-2.0': '/news/02-bref-2.0',
    '/docs/installation': '/docs/setup',
    '/docs/first-steps': '/docs/setup#whats-next',
    '/docs/runtimes/http': '/docs/runtimes/fpm-runtime',
    '/docs/websites': '/docs/use-cases/websites',
    '/docs/web-apps/docker': '/docs/deploy/docker',
    '/docs/installation/aws-keys': '/docs/setup/aws-keys',
    '/docs/environment/custom-domains': '/docs/use-cases/http/custom-domains',
    '/docs/aws-cdk': '/docs/deploy/aws-cdk',
    // TODO what's this url?
    '/docs/web-apps/index.md#assets': '/docs/use-cases/websites',
    '/docs/function/local-development': '/docs/local-development/event-driven-functions',
    '/docs/frameworks/laravel': '/docs/laravel/getting-started',
    '/docs/frameworks/symfony': '/docs/symfony/getting-started',
    '/docs/newsletters': '/docs/community#newsletters',
    '/docs/newsletters.html': '/docs/community#newsletters',
    '/docs/cron': '/docs/use-cases/cron',
    '/docs/cron.html': '/docs/use-cases/cron',
    '/docs/web-apps/cron': '/docs/use-cases/cron',
    '/docs/web-apps/cron.html': '/docs/use-cases/cron',
    '/docs/local-development': '/docs/local-development',
    '/docs/local-development.html': '/docs/local-development',
    '/docs/web-apps/local-development': '/docs/local-development',
    '/docs/web-apps/local-development.html': '/docs/local-development',
};
