module.exports.redirects = {
    '/slack': 'https://join.slack.com/t/brefworkspace/shared_invite/enQtNTcwMjU2NTcxNjAxLTIxYmM2MmRjMDkzYjdjYTNkMmE5NGI3YTcyZjc2ZGRjNTFmNjFmYzk5NWQ1YmVhMDkwNzExNzhjZThkZWM0ODE',
    '/#ecosystem': '/support',
    '/#plans': '/support',
    '/#enterprise': '/support',
    // TODO: add redirects for anchor links too
    '/docs/news': '/news',
    '/docs/news/01-bref-1.0': '/news/01-bref-1.0',
    '/docs/news/02-bref-2.0': '/news/02-bref-2.0',
    '/docs/installation': '/docs/setup',
    '/docs/first-steps': '/docs/setup#whats-next',
    '/runtimes/#bref-ping': '/docs/runtimes/runtimes-details#telemetry-ping',
    '/docs/runtimes/http': '/docs/runtimes/fpm-runtime',
    '/docs/runtimes/fpm-runtime#setup': '/docs/runtimes/fpm-runtime#usage',
    '/docs/runtimes/fpm-runtime#runtime': '/docs/runtimes/fpm-runtime',
    '/docs/runtimes/fpm-runtime#routing': '/docs/use-cases/http#how-it-works',
    '/docs/runtimes/fpm-runtime#binary-requests-and-responses': '/docs/use-cases/http/binary-requests-responses',
    '/docs/runtimes/fpm-runtime#cold-starts': '/docs/use-cases/http/advanced-use-cases#cold-starts',
    '/docs/websites': '/docs/use-cases/websites',
    '/docs/web-apps/docker': '/docs/deploy/docker',
    '/docs/installation/aws-keys': '/docs/setup/aws-keys',
    '/docs/environment/custom-domains': '/docs/use-cases/http/custom-domains',
    '/docs/aws-cdk': '/docs/deploy/aws-cdk',
    // TODO what's this url?
    '/docs/web-apps/index.md#assets': '/docs/use-cases/websites',
    '/docs/function/local-development': '/docs/local-development/event-driven-functions',
    '/docs/frameworks/laravel': '/docs/laravel/getting-started',
    '/docs/laravel/getting-started#assets': '/docs/laravel/getting-started#website-assets',
    '/docs/laravel/getting-started#file-storage-on-s3': '/docs/laravel/file-storage',
    '/docs/laravel/getting-started#public-files': '/docs/laravel/file-storage#public-files',
    '/docs/laravel/getting-started#laravel-queues': '/docs/laravel/queues',
    '/docs/laravel/getting-started#how-it-works-1': '/docs/laravel/queues#how-it-works',
    '/docs/laravel/getting-started#laravel-octane': '/docs/laravel/octane',
    '/docs/laravel/getting-started#persistent-database-connections': '/docs/laravel/octane#persistent-database-connections',
    '/docs/laravel/getting-started#caching': '/docs/laravel/caching',
    '/docs/laravel/getting-started#maintenance-mode': '/docs/laravel/maintenance-mode',
    '/docs/laravel/getting-started#laravel-passport': '/docs/laravel/passport',
    '/docs/frameworks/symfony': '/docs/symfony/getting-started',
    '/docs/newsletters': '/docs/community#newsletters',
    '/docs/newsletters.html': '/docs/community#newsletters',
    '/docs/cron': '/docs/use-cases/cron',
    '/docs/cron.html': '/docs/use-cases/cron',
    '/docs/web-apps/cron': '/docs/use-cases/cron',
    '/docs/web-apps/cron.html': '/docs/use-cases/cron',
    '/docs/web-apps/local-development': '/docs/local-development',
    '/docs/web-apps/local-development.html': '/docs/local-development',
};
