name: Build Docker images

on:
  push:
    paths:
      - runtime/**

jobs:
  publish:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build images
        run: make docker-images
